/**
 * Product  : Hiperium Project
 * Architect: Andres Solorzano.
 * Created  : 08-05-2009 - 23:30:00
 * 
 * The contents of this file are copyrighted by Andres Solorzano 
 * and it is protected by the license: "GPL V3." You can find a copy of this 
 * license at: http://www.hiperium.com/about/licence.html
 * 
 * Copyright 2014 Andres Solorzano. All rights reserved.
 * 
 */
package com.hiperium.commons.services.exception;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.validation.ConstraintViolation;

/**
 * This is a subclass of Exception and implements the properties needed to
 * manage errors generated by the Bean Validation API.
 * 
 * @author Andres Solorzano.
 * 
 */
public class PropertyValidationException extends Exception implements Serializable {

	/**
	 * The property serialVersionUID.
	 */
	private static final long serialVersionUID = -7946024942558905397L;

	/** The constraintViolations. */
	private Set<ConstraintViolation<?>> constraintViolations;
	
	/**
	 * 
	 * Class constructor.
	 * 
	 * @param constraintViolations
	 */
	public PropertyValidationException(Set<? extends ConstraintViolation<?>> constraintViolations) {
		if ( constraintViolations == null ) {
			this.constraintViolations = new HashSet<ConstraintViolation<?>>();
		}
		else {
			this.constraintViolations = new HashSet<ConstraintViolation<?>>(constraintViolations);
		}
	}

	/**
	 * Gets the constraintViolations property.
	 * 
	 * @return the constraintViolations.
	 */
	public Set<ConstraintViolation<?>> getConstraintViolations() {
		return constraintViolations;
	}
	
}
